name: myserver
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.3.0
  dotenv: ^4.2.0
  logging: ^1.2.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  http: ^1.0.0
  html_unescape: ^2.0.0

dev_dependencies:
  #http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
